#!/usr/bin/env ruby

iphones = [
  [640, 960],
  [640, 1136],
  [750, 1334],
  [1242, 2208]
]

def generate(w, h, src)
  dst = "#{w}x#{h}"

  print "#{src} #{dst}...\n"
  `mkdir -p #{dst}`
  `cp #{src}/*.png #{dst}`
  `mogrify -resize #{w} -crop x#{h}+0+0 #{dst}/*.png`
end

iphones.each do |size|
  w,h = size
  generate(w, h, "iPhone")
end

